/*
  HIH9130 example -  by Franz Stoiber

  History -----------------------------------------------------
  2020-01-19 V1.0
-------------------------------------------------------------

  Hardware ----------------------------------------------------
  controller: ESP32 Dev Module
  temp/hum sensor: HIH9130
  -------------------------------------------------------------

  ESP32 pin usage ---------------------------------------------
  Pin  3V3                          ... 3V3
  Pin  GND                          ... 0V
  Pin  D15/ADC2_3/TOUCH3/SPI-SS     ...
  Pin  D02/ADC2_2/TOUCH02           ...
  Pin  D04/ADC2_0/TOUCH00           ...
  Pin  D16/RX2                      ...
  Pin  D17/TX2                      ...
  Pin  D05/VSPI-SS                  ...
  Pin  D18/VSPI-SCK                 ...
  Pin  D19/VSPI-MISO                ...
  Pin  D21/I2C-SDA                  ...  SDA
  Pin  D03/RX0                      ...
  Pin  D01/TX0                      ...
  Pin  D22/I2C-SCL                  ...  SCL
  Pin  D23/VSPI-MOSI                ...
  Pin  EN/RESET                     ...
  Pin  VP only in                   ...
  Pin  VN only in                   ...
  Pin  D34/ADC1_6 only in           ...
  Pin  D35/ADC1_7 only in           ...
  Pin  D32/ADC1_4/TOUCH09           ...
  Pin  D33/ADC1_5/TOUCH08           ...
  Pin  D25/ADC2_8/DAC1              ...
  Pin  D26/ADC2_9/DAC2              ...
  Pin  D27/ADC2_7/TOUCH07           ...
  Pin  D14/ADC2_6/TOUCH06/SPI-CLK   ...
  Pin  D12/ADC2_5/TOUCH05/SPI-MISO  ...
  Pin  D13/ADC2_4/TOUCH04/SPI-MOSI  ...
  Pin  GND                          ... 0V
  Pin  VIN                          ...
  Pin  IO0 (only on breakout)       ...
  -------------------------------------------------------------
*/

//includes
#include "HIH9130.h"
#include <Wire.h>

//declarations for prg
String PrgName = "HIH9130 example";
String PrgVersion = "1.0";

//instance 24C32
HIH9130 myTH;

void setup() {
  Serial.begin(115200);
  Serial.print(PrgName);
  Serial.print("  V");
  Serial.println(PrgVersion);

  //init library Wire
  Wire.begin();
  Wire.setClock(400000);

  //init class HIH9130
  myTH.begin(HIH9130_DEFAULT_ADDRESS);
}

void loop() {
  myTH.readTempHum();
  Serial.print("temperature: ");
  Serial.print(myTH.Temp, 2);
  Serial.print(" °C, humidity: ");
  Serial.print(myTH.Hum, 2);
  Serial.println(" %rH");
  delay(5000);
}
